### ISSUE TITLE
get rid of global state

### ISSUE THREAD

**Issue by rubiii** [savonrb/httpi#73]
it prevents e.g. using multiple loggers for HTTPI in one project.
i would like to see all methods on the `HTTPI` module which deal with global state gone.
i already did this for several savonrb libraries including nori for the savon 2.0 release.

here's the list of methods that come to mind:
- `HTTPI.adapter=`
- `HTTPI.log=`
- `HTTPI.logger=`
- `HTTPI.log_level=`

maybe, if we changed the `HTTPI` module to a class, we could create `HTTPI` instances which hold these options. the static http request method on the new `HTTPI` class like `.post` could then be changed to shortcuts for creating a new instance with options and executing a request.

don't know if that's the best idea though.

**Comment by pcai** [comment]
I second this suggestion from @ioquatix to soft-deprecate this gem, rather than try to "get rid of global state" - compiling some reasons:
- as already mentioned, such a change would make it almost identical in form and function to faraday, so its not clear what the community gains from having 2 duplicative ways to solve the same problem
- maintenance bandwidth for this gem and other savon projects is already very minimal, and thus very precious. committing to a rewrite means spending significant effort to update not only this gem, but many dependents

So this translates roughly into:
- close all issues tracking threadsafety/state problems that would need major new features or rewrites to accomplish
- update documentation to reflect that the gem is in maintenance, and likely won't be releasing or accepting new features moving forward (we can take anything in progress on a case by case basis)
- publish a migration guide to something like faraday?

I am open to alternative ideas, but at this point it would require someone to be extremely persuasive and simultaneously generous with their time for it to be reasonable

**Comment by pcai** [comment]
Closing this as a follow-up to my prior message - please see also https://github.com/savonrb/httpi/issues/238. thanks
